name: Generate CodeCoverage Badge
on:
  push:
    branches: [ master ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run unit tests with coverage
        run: |
          npm run coverage
          STATEMENTS=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct') 
          echo "COVERAGE=$(echo ${STATEMENTS}%)" >> $GITHUB_ENV
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 51a8c6c4f125bd6ec25a14a6f12e28bc
          filename: vue-timeago3_coverage.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          namedLogo: vitest
          color: brightgreen
