name: main
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npx prettier --check "src/**/*.js"
      - name: Vue TSC
        run: npx vue-tsc --noEmit
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Unit Tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npx vite build
