name: Create Release
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: "14"
            cache: "npm"
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - name: npm config
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm run release --ci --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}